planning_plugin: stomp_moveit/StompPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1
stomp_moveit:
  num_timesteps: 40
  num_iterations: 60
  num_iterations_after_valid: 5
  num_rollouts: 20
  max_rollouts: 30
  exponentiated_cost_sensitivity: 0.5
  control_cost_weight: 0.1
  delta_t: 0.1
  path_marker_topic: /stomp_trajectory
